create table if not exists public.wedding_rsvp (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  attendance text not null check (attendance in ('attend', 'absent')),
  guests text not null,
  message text,
  created_at timestamptz not null default now()
);

alter table public.wedding_rsvp enable row level security;

drop policy if exists "Guests can submit wedding RSVP" on public.wedding_rsvp;

create policy "Guests can submit wedding RSVP"
on public.wedding_rsvp
for insert
to anon
with check (true);
